---
title: "Más ejemplos de problemas con valores iniciales (EDOs)."
author: "Análisis Numérico."
date: "Abril 2024"
output: 
  html_document:
    toc: true
    toc_depth: 1
    theme: cerulean
---





<style>
body {
text-align: justify}
</style>



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(knitr)
library(tidyverse)
library(pracma)
library(plotly)
library(polynom)
library(matlib)
```


Aproxima la solución de los siguientes problemas con valores iniciales con los diferentes métodos provistos por las funciones del package *pracma*.  Comenta la comparación entre las aproximaciones obtenidas y la solución *exacta* (en caso que se indique).




1. $y'=cos(2t)+sen(3t)$, $0\leq t\leq 1$, $y(0)=1$.  Solución exacta 
\begin{equation}
y(t)=\frac{1}{2}sen(2t)-\frac{1}{3}cos(3t)+\frac{4}{3}.
 \end{equation}
 
 
 
 2. 
 
 \begin{equation}
 y'=\frac{y}{t}-(y/t)^2, \quad 1\leq t \leq 4, \quad y(1)=1
 \end{equation}
 
 Solución exacta.
 
 \begin{equation}
 y(t)=\frac{t}{1+log\,t}
 \end{equation}
 
 3. 
 
 \begin{equation}
 y'=(t+2t^3)y^3-ty, \quad 0\leq t \leq 2, \quad y(0)=\frac{1}{3}
 \end{equation}
 
 Solución exacta.
 
 \begin{equation}
 y(t)=\frac{1}{\sqrt{3+2t^2+6e^{t^2}}}
 \end{equation}
 
 
 
 
4. 

\begin{equation}
\begin{aligned}
y'_1&=y_2, &\qquad y_1(0)=1;\\
y'_2&=-y_1-2e^t+1, &\qquad y_2(0)=0;\\
y'_3&=-y_1-e^t+1, &\qquad y_3(0)=1;
\end{aligned}
\end{equation}

para $0\leq t \leq 2$. Donde las soluciones exactas son:


\begin{equation}
\begin{aligned}
y_1(t)&=cos\,t+ sen\,t-e^t+1\\
y_2(t)&=-sen\, t+cos\, t-e^t\\
y_3(t)&=-sen\,t+cos\,t
\end{aligned}
\end{equation}

5. 

\begin{equation}
\begin{aligned}
y'_1&=3y_1+2y_2-(2t^2+1)e^{2t}, &\qquad y_1(0)=1;\\
y'_2&=4y_1+y_2+(t^2+2t-4)e^{2t}, &\qquad y_2(0)=1;
\end{aligned}
\end{equation}

para $0\leq t \leq 1$. Donde las soluciones exactas son:


\begin{equation}
\begin{aligned}
y_1(t)&=\frac{1}{3}e^{5t}-\frac{1}{3}e^{-t}+e^{2t}\\
y_2(t)&=\frac{1}{3}e^{5t}+\frac{2}{3}e^{-t}+t^2e^{2t}
\end{aligned}
\end{equation}


6. 

\begin{equation}
\begin{aligned}
y'_1&=3y_1+2y_2-y_3-1-3t-2\, sen\,t, &\qquad y_1(0)&=5;\\
y'_2&=y_1-2y_2+3y_3+6-t+2\,sen\,t+cos\, t, &\qquad y_2(0)&=-9;\\
y'_3&=2y_1+4y_3+8-2t, &\qquad y_3(0)&=-5;
\end{aligned}
\end{equation}

para $0\leq t \leq 2$. Donde las soluciones exactas son:


\begin{equation}
\begin{aligned}
y_1(t)&=2e^{3t}+3e^{-2t}+t\\
y_2(t)&=-8e^{-2t}+e^{4t}-2e^{3t}+\,sen\,t\\
y_3(t)&=2e^{4t}-4e^{3t}-e^{-2t}-2
\end{aligned}
\end{equation}





7. $y''-2y'+y=t\,e^t-t$, $0\leq t\leq 1$, $y(0)=y'(0)=0$.

Solución exacta:

\begin{equation}
y(t)=\frac{1}{6}t^3e^t-te^t+2e^t-t-2.
\end{equation}

8. $y'''+2y''-y'-2y=e^t$, $0\leq t\leq 3$, $y(0)=1$, $y'(0)=2$, $y''(0)=0$. 

Solución exacta: 

\begin{equation}
y(t)=\frac{43}{36}e^t+\frac{1}{4}e^{-t}-\frac{4}{9}e^{-2t}+\frac{1}{6}te^t.
\end{equation}


